### PR TITLE
Remove usermanager

### LINKED ISSUE #44: Add green dot for logged in users and grey for others instead repetitive text
It is not a big deal but when I see all those "logged in" and "logged out" text below usernames bugs me. I propose to add a green dot for logged in user and grey dot for logged out users. 

The dot could be partially overlapping the profile photo or at the end of a user's name (aligned right).

### LINKED ISSUE #49: Add green dot for logged in users and grey for others instead repetitive text
It is not a big deal but when I see all those "logged in" and "logged out" text below usernames bugs me. I propose to add a green dot for logged in user and grey dot for logged out users. 

The dot could be partially overlapping the profile photo or at the end of a user's name (aligned right).

### LINKED ISSUE #67: displaying lightdm user in switch-user menu
screenshot from 2018-07-08 18 48 00

my lightdm.conf

```
[SeatDefaults]
greeter-session=pantheon-greeter

[UserAccounts]
minimum-uid=500
hidden-users=nobody nobody4 noaccess lightdm
hidden-shells=/bin/false /usr/sbin/nologin
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/60618402-displaying-lightdm-user-in-switch-user-menu?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #71: Close popover before switching user
If you switch users, then switch back to the original user, the popover is (sometimes?) still open, causing you to click it again when unlocking. Instead, we should ensure the popover is closed before switching users.

### LINKED ISSUE #127: User name displays as (null) in power menu
Username is 'James & Stephanie' and displays as **(null)** in the wingpanel power menu. Assuming that ampersand (&) breaks this, but will leave that for the developers to confirm.

Wingpanel version below:

`~$ apt-cache policy wingpanel`
`wingpanel:`
`  Installed: 2.3.2+r454+pkg48~ubuntu5.1.5.1`

Screenshot attached.
Screenshot from 2020-06-21 16-38-56

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/91817383-user-name-displays-as-null-in-power-menu?utm_campaign=plugin&utm_content=tracker%2F57362887&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57362887&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #146: Popover widget does not show new user
## What Happened

Popover widget does not show new user when a new user is added.

screen-capture

Segmentation fault at the end of the gif seems to be a separate issue.

## Expected Behavior

Newly added user should be shown in popover widget.

## Steps to Reproduce

1. Add new user from switchboard.
2. Click session indicator.

## Platform Information

eOS6 daily. Master session indicator.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95369888-popover-widget-does-not-show-new-user?utm_campaign=plugin&utm_content=tracker%2F57362887&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F57362887&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #158: Screen locks after switching user
## What Happened

With two users logged in simultaneously, use the session indicator to switch to the other user by double clicking on their entry in the popover.  The greeter appears and the other users password is entered.  The other users screen appears briefly by the screen then locks and goes black.  Pressing a key brings up the the greeter again and a second login is required.

This issue is similar to, and may be related to issue #139 but that issue did not mention two users.

## Expected Behavior

Switching between two logged in users should only require one password entry.

## Steps to Reproduce

1. Create two users A and B
2. Log in as A
3. Double click on entry B in the session indicator
4. Log in as B
5. Double click on entry A in the session indicator
6. Log in as A
7. Screen goes black after a brief glimpse of A's desktop
8. Log in as A again - logs in normally

## Platform Information

Elementary 6 daily

### PR DESCRIPTION
**Pull request by danirabbit**
Closes elementary/quick-settings#44 
Closes elementary/wingpanel-indicator-session#67 
Closes elementary/wingpanel-indicator-session#71 
Closes elementary/wingpanel-indicator-session#127 
Closes elementary/wingpanel-indicator-session#146 
Closes elementary/wingpanel-indicator-session#158 

Proposing to remove the userlist/quick user switching completely. It seems like this feature only really exists to pre-select an account on the Greeter which seems kind of pointless. In the interest of https://github.com/elementary/wingpanel/discussions/446, I'd like to [stripe this menu down](https://github.com/elementary/wingpanel-indicator-session/pull/174) and start adding in some of the quick settings actions that folks have been asking for

### CODE REVIEW

**Review by zeebok — APPROVED** [review]
Code looks good. Should we have some kind of indication of whom is logged currently? Maybe the new logout button could say in the tooltip or something?

**Comment by danirabbit** [comment]
That's a good question. I mainly opened this hoping to get some feedback from people who maybe use these features, but so far I haven't heard anything :sweat_smile:

I know @jeremypw and @ryonakano worked on reviewing the PR for this feature so maybe they have opinions about the utility of showing the name of the logged in user?

**Comment by TomiOhl** [comment]
> Should we have some kind of indication of whom is logged currently?

Tbh I liked seeing my username and profile pic there, but never used it to switch users.

**Comment by jhaygood86** [comment]
My own preference would be to keep displaying current user and profile but remove fast user switching. It's pretty rare for devices to be shared, and logging out and back in is probably acceptable for those devices that are shared

**Comment by zeebok** [comment]
Likewise, I do like seeing my profile pic and name

**Comment by jeremypw** [comment]
I do sometimes use user switching when developing in order to try something as a different user without losing the current user set up (which would happen if I logged out), so I would be sorry to see this go.

**Pull request closed without merging**
