### PR TITLE
Use async versions of Bus.get_proxy

### PR DESCRIPTION
**Pull request by davidmhewitt**
There's quite a lot of DBus code here that was synchronous, maybe things will be a _teeny bit_ more responsive if we use async instead.

### CODE REVIEW

**Comment by tintou** [comment]
I don't think that we should be using Gtk in an async method though :confused: maybre wrap it in a `Idle.add()` :thinking:

**Comment by davidmhewitt** [comment]
It would be bad to do Gtk stuff in a different thread, sure. But there are no extra threads here. Is there something I don't know about async?

**Comment by tintou** [comment]
Vala by itself isn't using another thread for async but any other call (bound by `yield`) can use an API like `g_task_run_in_thread` but let's assume that we are always returning in the right thread here (which the documentation implies)

**Comment by davidmhewitt** [comment]
Yes, but `g_task_run_in_thread` is specifically designed to perform its callbacks and return a result on the calling thread, which is the main thread here.

The whole concept of async methods in GLib style libraries is so that you **don't** have to worry about threads. If some library is modifying the thread context and not setting it back just because you called an async method, then that's a buggy library. I think we can assume that GLib itself is safe.

**Review by tintou — APPROVED** [review]

**Pull request merged**
