### PR TITLE
Show & close opened apps

### PR DESCRIPTION
**Pull request by donadigo**
This branch adds a new UI and functionality for showing opened apps that will be closed when leaving the session. The end session dialog now contains a list of opened apps and their icons, if there are more than `MAX_APP_ICONS` apps (currently 6), a label will be shown with how many apps there are beside those that are displayed.

When leaving the session, the indicator will initially request all user visible windows to close resulting in closing applications themselves. While that is going in the background, the `ShutdownAction` sets up a timer which after it's done will send a SIGKILL to all windows to force close them. The amount of timeout is defined in the `KILL_TIMEOUT_SECONDS` constant (currently 6). Clicking "cancel" in the dialog will stop the timeout as well as all other actions `ShutdownAction` set up.

This branch introduces two new dependencies: `libbamf3` and `libwnck-3.0`.

Notes:
* Can the `OpenedAppsBox` be transformed into a `Gtk.Grid`? I haven't figured out a way to pack the label always at the end of a grid.

Testing:
You can test this branch without actual reboot / shutdown or logout by commenting out diff lines 153 - 163.

### CODE REVIEW

**Comment by cassidyjames** [comment]
Here is the demo that was shared in Slack:
shutdown-dialog

**Comment by donadigo** [comment]
Noting: this probably requires or it would be good to implement `org.gnome.SessionManager` at this point. It seems like `systemd` and `login1` provide only bare-bones shutdown / restart methods, so the process of closing apps and properly handling them has to be done on the client side here.

**Comment by cassidyjames** [comment]
@donadigo any chance to resolve conflicts? :grimacing:

**Comment by donadigo** [comment]
@cassidyjames conflicts resolved.

**Comment by torikulhabib** [comment]
fix problem at greeter @donadigo 
very long time to show dialog.

**Comment by donadigo** [comment]
@danrabbit and how would we show a lot of apps (when the listbox becomes too big)?

There is no way AFAIK, you either have to implement the interface in gala (https://github.com/elementary/gala/issues/68) or use X-specific API's like libbamf. We could conditionally compile this stuff though.

**Comment by danrabbit** [comment]
@donadigo I'd imagine we'd just scroll it yeah?

**Comment by tintou** [comment]
You probably already know my opinion about this, I'm against introducing libbamf and libwnck at this

**Comment by donadigo** [comment]
@tintou I would not like too. What I'm concerned more about is that there's no standard way of doing that on Wayland and it'll be a lot of work in WM & spec before we would actually get the interface of doing exactly the same thing as is now.

**Comment by 4jNsY6fCVqZv** [comment]
@donadigo The idea is in the room for a while now. Are you still working on an implementation?

**Comment by donadigo** [comment]
@4jNsY6fCVqZv besides making the box a list, I'm not interested in pushing something that will be rejected anyway due to the usage of libbamf & libwnck. I don't understand this decision as
1. there is no replacement for it 
2. there won't be any replacement anytime soon for a probably considerable amount of time that this branch would be already live

The commits I pushed are more for personal use.

**Comment by 4jNsY6fCVqZv** [comment]
The concerns about libbamf and libwnck concern only their X -specific dependencies? When does elementary OS want to switch to Wayland? Do both libbamf and libwnck have no issues to enable Wayland support? If there are currently no alternatives, wouldn't it be possible to discuss a workaround for the meantime? Or is that just not useful for just one feature? How strong are the dependencies of the two projects on X? Would Wayland and X have to be completely installed and run in parallel?

**Comment by donadigo** [comment]
These two libs depend heavily on X and they wouldn't work on Wayland. If we move to Wayland, and again that is far from now even if it's Juno+1, we would need to basically recreate API's that these libs provide, these would depend on the things elementary OS provides (e.g gala).

**Comment by 4jNsY6fCVqZv** [comment]
Do you think it makes sense to discuss this with the team again?
And how complicated would it be to create such API's yourself so that there is no dependency on the libraries mentioned and that they also allow Wayland to run smoothly when elementary OS development gets to that point.
Or would it also be conceivable to contribute code to existing projects?

**Comment by donadigo** [comment]
@4jNsY6fCVqZv I brought this up a couple of times now and I don't think asking about it yet again will yield any movement here. I made sure that the branch can be compiled without all the problematic dependencies but it seems like the team isn't interested. Maybe I'll try to bring it up again.

**Comment by 4jNsY6fCVqZv** [comment]
@donadigo Thank you for your investigative work. Maybe the time for your idea just isn't there yet. I am curious how things will develop.

**Pull request closed without merging**
