### PR TITLE
Cleanup middle click shortcut code

### PR DESCRIPTION
**Pull request by davidmhewitt**
As per @donadigo and @Philip-Scott 's comments in #6

There was a leftover timestamp parameter from when I was debugging the focus issues and I've improved the logic of the code.

### CODE REVIEW

**Comment by Philip-Scott** [comment]
Code-wise, i approve. I just have to test it and make sure `shutdown_dialog.set_transient_for (indicator_icon.get_toplevel () as Gtk.Window);` doesn't break anything :) 

Thanks for doing the changes!

**Comment by davidmhewitt** [comment]
@Philip-Scott That line isn't strictly necessary when you open the dialog via middle clicking the indicator. However, it is needed when you open a dialog from the indicator menu; it brings it into focus correctly.

You'll notice that `set_transient_for` was used in the original code for opening the dialogs :slightly_smiling_face:

**Comment by Philip-Scott** [comment]
Hmmm.... Looks like the dialog is not grabing focus correctly. If i were to guess though, it's wingpanel's fault though but it might be worth a look :)

**Comment by davidmhewitt** [comment]
@Philip-Scott Yep, it's wingpanel's fault. I mentioned that in #6 and I've proposed a fix for wingpanel here that just needs some testing:
https://code.launchpad.net/~davidmhewitt/wingpanel/fix-focus/+merge/320544

**Pull request merged**
