### PR TITLE
Add link to settings

### PR DESCRIPTION
**Pull request by cassidyjames**
Adds a link to user account settings beneath the user accounts. Handy to be able to add or remove a user from the related indicator.

user-accounts-settings-indicator

### CODE REVIEW

**Comment by Philip-Scott** [comment]
I'm honestly -1 on adding a link to the account settings in here. Adding/Removing users is something that is usually done only once per system, not something like Network or Sound settings

**Comment by augustin-b** [comment]
This is good idea. I good intuitive way could be to link the avatar + user name area. Very same behavior like in volume indicator to open Music app.

**Comment by cassidyjames** [comment]
@augustin-b then that causes inconsistent behavior where clicking some users switches to them, while clicking others takes you to that user's settings. I think the current behavior is correct here.

@Philip-Scott I could argue that setting up networking or audio settings is something most people are only going to do once or twice, though. ;) It's always super awkward for me when I want to change my avatar or add an account to my computer (i.e. for my wife after installing) and I go to the related indicator, expecting a link to settings like every single other indicator we ship.

**Comment by cassidyjames** [comment]
@elementary/ux thoughts?

**Comment by harveycabaguio** [comment]
This doesn't really seem like something you'd do often enough to warrant a menu item.

**Pull request merged**
