### PR TITLE
Use gnome-session interfaces to end session where possible

### PR DESCRIPTION
**Pull request by davidmhewitt**
Previously the `EndSessionDialog` class handled all the logic for which DBus interfaces to call when a logout/reboot/shutdown action was confirmed.

It was calling methods like `terminate` and `reboot` on `org.freedesktop.login1`, which is fine if you don't have an active session (i.e. you're in greeter mode). But when we're in a session, it's a lot cleaner to ask `gnome-session` to do these things for us as it handles talking to all of the active applications and asking them to close cleanly, rather than just killing them.

So I've moved that logic out of the dialog and it's only UI code that remains. Now, when we're in an active session and a logout/shutdown button is pressed, we call the logout/reboot/shutdown methods on `org.gnome.SessionManager`, which in turn spawns the `EndSessionDialog` via DBus and we either confirm or cancel that request depending on the outcome of the dialog.

If we're not in an active session, we spawn the dialog manually and then call the `org.freedesktop.login1` methods as before.

I found that logging out on our focal builds was really hit and miss. Most of the time you'd just end up sat looking at your wallpaper with no wingpanel/plank etc and never get kicked back to the greeter. Then you'd have to power cycle the machine to get it working again. This fixes that.

It also hopefully closes applications in the session a bit more cleanly, so hopefully we'll see a few more things saving their state a bit better.

### CODE REVIEW

**Comment by jeremypw** [comment]
After installing the latest masters of winpanel, plank and polkit-agent as well as that of the notification session indicator, wingpanel crashes when the session indicator icon is clicked on.  This PR does not fix it.
Backtrace is:
```
Thread 1 "wingpanel" received signal SIGSEGV, Segmentation fault.
0x00007fffca9bb4bb in session_indicator_real_get_widget (base=0x555555bfe960) at /media/jeremy/Shared/shared_data/Vala/Elementary/wingpanel/wingpanel-indicator-session/src/Indicator.vala:132
132	                log_out_grid.accel_string = keybinding_settings.get_strv ("logout")[0];
(gdb) bt
#0  0x00007fffca9bb4bb in session_indicator_real_get_widget (base=0x555555bfe960) at /media/jeremy/Shared/shared_data/Vala/Elementary/wingpanel/wingpanel-indicator-session/src/Indicator.vala:132
#1  0x00007ffff7bc812c in wingpanel_indicator_get_widget (self=0x555555bfe960) at /media/jeremy/Shared/shared_data/Vala/Elementary/wingpanel/wingpanel/lib/Indicator.vala:71
#2  0x0000555555569519 in wingpanel_widgets_indicator_entry_get_indicator_widget (self=0x5555559a2960) at /media/jeremy/Shared/shared_data/Vala/Elementary/wingpanel/wingpanel/src/Widgets/IndicatorEntry.vala:27
#3  0x0000555555568017 in wingpanel_services_popover_manager_set_current_indicator (self=0x555555949e60, value=0x5555559a2960) at /media/jeremy/Shared/shared_data/Vala/Elementary/wingpanel/wingpanel/src/Services/PopoverManager.vala:53
#4  0x0000555555568b57 in __lambda15_ (_data6_=0x55555590df00, e=0x5555559b0f20) at /media/jeremy/Shared/shared_data/Vala/Elementary/wingpanel/wingpanel/src/Widgets/IndicatorEntry.vala:110
#5  0x0000555555568bd6 in ___lambda15__gtk_widget_button_press_event (_sender=0x5555559a2960, event=0x5555559b0f20, self=0x55555590df00) at IndicatorEntry.c:479
#6  0x00007ffff691d7fb in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff72c910d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff72dc05e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff72e40af in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff72e512f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff6a65534 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff691a86e in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff691c948 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff642d765 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#15 0x00007ffff645df92 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#16 0x00007ffff78f8417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#17 0x00007ffff78f8650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff78f86dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff75afefd in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#20 0x0000555555560f69 in wingpanel_main (args=0x7fffffffdf58, args_length1=1) at /media/jeremy/Shared/shared_data/Vala/Elementary/wingpanel/wingpanel/src/Wingpanel.vala:24
#21 0x0000555555560fac in main (argc=1, argv=0x7fffffffdf58) at /media/jeremy/Shared/shared_data/Vala/Elementary/wingpanel/wingpanel/src/Wingpanel.vala:21
(gdb) 

```

**Comment by jeremypw** [comment]
Reverting to the released version of the session indicator fixes the crash.  Looks like that issue needs fixing first.

**Comment by jeremypw** [comment]
I now realise this project is now a Focal branch so I need to work on it with Focal - which I cannot do at the moment.

**Comment by davidmhewitt** [comment]
Yes, there's nothing Focal specific about this branch/PR, and I think the necessary versions of wingpanel, plank and polkit agent are already released to stable on Hera now.

There was talk that we may want to backport this patch to Hera, but to do so we'd have to merge this branch directly into the `juno` branch to avoid commit https://github.com/elementary/wingpanel-indicator-session/commit/ef60783a94fdbf955e27f9a1aced94a078ad95a3 which breaks compatibility with Hera.

**Comment by jeremypw** [comment]
But the Focal specific master has been merged into this now so it does not run on Hera. It needs to be rebased on a commit prior to ef60783 and a PR specifying merging at that point made (is that possible?).  Will GitHub then stop requiring merging master?

**Comment by jeremypw** [comment]
It would be nice to have this in Hera unless Odin release is imminent (which it does not seem to be).

**Pull request merged**
